version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: .
    volumes:
      - ./public:/app
